# Generated by Django 4.2.20 on 2025-03-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(choices=[('ОЖИДАНИЕ', 'ОЖИДАНИЕ'), ('УПАКОВКА', 'УПАКОВКА'), ('ОТГРУЗКА', 'ОТГРУЗКА'), ('ПРИБЫТИЕ', 'ПРИБЫТИЕ'), ('УСПЕХ', 'УСПЕХ')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('ОЖИДАНИЕ', 'ОЖИДАНИЕ'), ('ОБРАБОТКА', 'ОБРАБОТКА'), ('УСПЕШНО', 'УСПЕШНО'), ('ОТМЕНЕНА', 'ОТМЕНЕНА'), ('НЕУДАЧНАЯ', 'НЕУДАЧНАЯ')], default='PENDING', max_length=20),
        ),
    ]
